version: "3.8"
services:
  pvpc-influxdb:
    image: ghcr.io/multithefranky/pvpc-influxdb
    container_name: pvpc-influxdb
    environment:
      - INFLUXDB_URL="http://influxdb:8086"
      - INFLUXDB_TOKEN="my-token"
      - INFLUXDB_ORG="my-org"
      - INFLUXDB_BUCKET="my-bucket"
      - CRON="5 0 * * *" # 0:05 every day
    restart: unless-stopped