# Action to run on pull request creation
name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run Yarn
        run: yarn
      - name: Run Yarn Build
        run: yarn build
      - name: Run Yarn Lint
        run: yarn lint
  auto-approve:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pull-requests: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved automated PR"
