name: "release"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run Yarn
        run: yarn
      - name: Run Yarn Build
        run: yarn build
      - name: Run Yarn Lint
        run: yarn lint
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release v${{ github.ref }}"